

function Home({ children }) {
  // const [jobs, setJobs] = useState([])


  return (
    <>
      {/* <Head>
        <title>Talentdrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Banner />
        <TrustedCompany />
        <Cards>
          {children}
         
        </Cards>
      </Layout> */}
    </>
  );
}
export default Home

